@startuml DiagramaClases

skinparam note {
  BackgroundColor #cce5ff
  BorderColor #336699
  FontStyle italic
}

object Usuario<<Entity>> {
    +correo
    +contraseña
    +nombre
}
note right: {incompleta, disjunta}


object Cliente<<Entity>> {
    +tarifaActual
    +fechaNacimiento
    +/alquilerActivo
    +borrado[0..1]
}
note left
'''
 **R.F.01.**. Registro de usuario.
 La contraseña tendrá 8 dígitos.
 **R.N.01.** No eliminar usuarios
 que tengan alquiler activo.
 **R.N.02.**. Evitar que los usuarios
 alquilen 2 vehículos simultáneamente.
 **R.N.04.** Edad mínima de 12 años.
'''
end note

object Pago<<Entity>> {
    +/tipoPago
    +cantidad
    +fecha
}
'Tipo pago puede ser o mensual o individual


object TecnicoMantenimiento<<Entity>> {
    +/fechaUltimoServicio
    +borrado[0..1]
}

object Reparacion<<Entity>> {
    +fechaInicio
    +fechaFin
    +detalles
}

object Valoracion<<Entity>> {
    +puntuacion
    +comentario [0..1]
}

/'
La distancia recorrida la cuenta el vehículo con un
medidor incorporado y solo se registra cuando termina el recorrido.
Por eso mismo no es derivada de lugar inicio o fin, porque si no si acabas
en el mismo sitio la distancia recorrida sería 0.
'/
object Alquiler<<Entity>> {
    +fechaHoraInicio
    +fechaHoraFin [0..1]
    +distanciaRecorrida [0..1]
    +/costo [0..1]
    +/lugarInicio
    +/lugarFin [0..1]
}

/'
La localización del vehículo se muestra cuando se guarda el vehículo.
No se guarda localización por GPS.
'/
object Vehiculo<<Entity>> {
    +/estado
    +/kilometraje = 0.00
    +/numeroUsos = 0
    +/localizacion [0..1]
    +borrado [0..1]
}
note right
'''
 **R.N.03** Si usos >50 o kilometraje>500
 estado=="mantenimiento pendiente".
 **R.N.05.** Cambio de estado vehículo.
'''
end note
note left of Vehiculo: {completa, disjunta}

object Estacion<<Entity>> {
    +nombre
    +/numeroVehículos
    +borrado[0..1]
}

object Enganche<<Entity>> {
    +numero
    +/estado
    +borrado[0..1]
}
note left
'''
 **R.N.06.** Cambio de estado enganche.
'''
end note

object Bicicleta<<Entity>> {
    +tipoBici
}

object PatineteElectrico<<Entity>> {
    +autonomiaBateria
}

Usuario <|-- Cliente
Usuario <|-- TecnicoMantenimiento

Enganche "*"--* Estacion : pertenece a >

'Relación directa valoraciones'
Alquiler "1"--"*" Valoracion : pone >
Valoracion "*"--* Vehiculo : recibe <

TecnicoMantenimiento "1"--"*" Reparacion : realiza >
Reparacion "*"--* Vehiculo : recibe <

Enganche "1" --"1" Alquiler: inicia/termina en <


'Relacion de Alquileres'
Cliente "1"--"*"  Alquiler: realiza >
 
Alquiler "*"--"1" Vehiculo: de

'Relacion Pago'
Cliente *--"*" Pago
Pago "0..1"--"0..1" Alquiler

Vehiculo <|-- Bicicleta
Vehiculo <|-- PatineteElectrico


@enduml