@startuml DiagramaClases

skinparam note {
  BackgroundColor #cce5ff
  BorderColor #336699
  FontStyle italic
}

class Usuario {
    +nombre
    +correo
    +contraseña
}

class Cliente {
    +tarifaActual
}

class TécnicoMantenimiento {
    +fechaÚltimoServicio
}

class Valoración {
    +puntuacion
    +comentario [0..1]
}

class Alquiler {
    +inicio
    +duracion
    +costo
}

class Vehículo {
    +estado
    +kilometraje
    +numeroUsos
    +ubicación
    +valoraciones
}

class Estación {
    +estado
    +zona
    +númeroVehículos
    +valoraciones
}

class Bicicleta {
    +tipoBici: str
}

class PatineteEléctrico {
    +autonomíaBatería
}

Usuario <|-- Cliente
Usuario <|-- TécnicoMantenimiento

'Relación directa valoraciones'
Cliente "1"--"*" Valoración : pone
Valoración "*"--"1" Vehículo : recibe
Valoración "*"--"1" Estación : recibe

Estación"1..*" -- "*"Vehículo : tiene

'Relacion de Alquileres'
Cliente "1"--"*"  Alquiler: tiene
'Requisitos seguidos de relacion a linkear'
note on link
  **RN-001:** No eliminar usuarios que tengan alquiler activo
end note
 
Alquiler "*"--"1" Vehículo: de

Vehículo <|-- Bicicleta
Vehículo <|-- PatineteEléctrico

@enduml