@startuml
object Cliente1 {
  +nombre="Ana López"
  +correo=analop@gmail.com
  +contraseña=11111111

}
object Cliente2 {
  +nombre="Carlos Ruiz"
  +correo=carlosrui@gmail.com
  +contraseña=11112222
}
object Bicicleta1 {
  +estado="Disponible"
  +kilometraje=120 km
  +numeroUsos=23
  +tipoBici
}
object Patinete1 {
    +estado="Disponible"
  +kilometraje=100 km
  +numeroUsos=8
  +autonomiaBateria
}
object Estacion1 {
  nombre = "Reina Mercedes"
  vehiculosDisponibles = 2
}
object Estacion2 {
  nombre = "Cartuja"
  vehiculosDisponibles = 0
}
object Estacion3 {
  nombre = "Los Bermejales"
  vehiculosDisponibles = 1
}
object Alquiler1 {
  inicio= 12/11/2025
  duracion = "25 min"
  coste = "2.50€"
}
object Alquiler2 {
  inicio= 25/03/2026
  duracion = "60 min"
  coste = "5.80€"
}
Cliente1 --> Alquiler1 : realiza
Cliente2 --> Alquiler2 : realiza
Alquiler1 --> Bicicleta1 : usa
Alquiler2 --> Patinete1 : usa
Bicicleta1 --> Estacion3 : devuelto en
Patinete1 --> Estacion2 : devuelto en
@enduml
