@startuml DiagramaClases

object Usuario1 {
    +Fernando
    +fernando@hotmail.com
    +123456A
}

object Usuario2 {
    +Felipe
    +felipe@gmail.com
    +234855C

}

object Cliente {
    +mensual
}

object TécnicoMantenimiento {
    +28-10-2025
}

object Valoración1 {
    +5/5
    +null
}

object Valoración2 {
    +3/5
    +Me cuesta enganchar la bici
}

object Alquiler {
    +28-10-2025 15:44:02
    +15.5
    +0.0
}

object Vehículo {
    +disponible
    +30.2
    +20
    +Reina Mercedes
}

object Estación {
    +ocupada
    +Reina Mercedes
    +13
}

object Bicicleta {
    +individual
}


Usuario1 <|-- Cliente
Usuario2 <|-- TécnicoMantenimiento

'Relación directa valoraciones'
Cliente -- Valoración1 : pone
Cliente -- Valoración2 : pone
Valoración1 -- Vehículo : recibe
Valoración2 -- Estación : recibe

Estación -- Vehículo : tiene

'Relacion de Alquileres'
Cliente --  Alquiler: tiene
 
Alquiler -- Vehículo: de

Vehículo <|-- Bicicleta

@enduml