@startuml DiagramaClases

skinparam note {
  BackgroundColor #cce5ff
  BorderColor #336699
  FontStyle italic
}

object Usuario1 {
    nombre= "Ana López"
    correo= analop@gmail.com
    contraseña= 11111111
}
note right: {incompleta, disjunta}
note left of Usuario1
'''
**R.N.15.** Contraseña de más de 8 caracteres
'''
end note

object Usuario2 {
    nombre= "Felipe Fernández"
    correo= felipe@gmail.com
    contraseña= 234855CA
}
note left: {incompleta, disjunta}
note right of Usuario2
'''
**R.N.15.** Contraseña de más de 8 caracteres
'''
end note


object Cliente1 {
    tarifaActual= mensual
    fechaNacimiento= 01/10/2000
    /alquilerActivo= False
    borrado= False
}
note left
'''
**R.N.01.** Edad mínima de 12 años.
**R.N.02.** No eliminar usuarios
que tengan alquiler activo.
'''
end note

object Pago1 {
    /tipoPago= individual
    cantidad= 5.99
    fecha= 27/10/2025
}
'Tipo pago puede ser o mensual o individual


object TecnicoMantenimiento1 {
    /fechaFinUltimoServicio= 22/10/2025
    borrado= False
}

object Reparacion1 {
    fechaInicio= 20/10/2025
    fechaFin= 22/10/2025
    detalles= "El vehículo tenía una rueda pinchada"
}



object Valoracion1 {
    puntuacion= 5
    comentario= null
}
note right
'''
**R.N.16.** Valoración con puntuación del 1 al 5
'''
end note

/'
La distancia recorrida la cuenta el vehículo con un
medidor incorporado y solo se registra cuando termina el recorrido.
Por eso mismo no es derivada de lugar inicio o fin, porque si no si acabas
en el mismo sitio la distancia recorrida sería 0.
'/
object Alquiler1 {
    fechaHoraInicio= 28/10/2025 15:44:02
    fechaHoraFin= 28/10/2025 15:55:23
    distanciaRecorrida= 3.3
    /costo= 0.0
    /lugarInicio= La Torre del Oro
    /lugarFin= Reina Mercedes
}
note right
'''
**R.N.03.** Evitar que los usuarios
alquilen 2 vehículos simultáneamente.
**R.N.12.** Precio alquiler con mensualidad.
**R.N.13.** Coger solo vehículos disponibles.
**R.N.14.** Dejar vehículo solo en enganches libres.
'''
end note

/'
La localización del vehículo se muestra cuando se guarda el vehículo.
No se guarda localización por GPS.
'/
object Vehiculo1 {
    /estado= disponible
    /kilometraje = 30.2
    /numeroUsos = 20
    /localizacion = Estación Reina Mercedes Enganche 1
    borrado= False
}
note right
'''
**R.N.04.** No eliminar vehículos que estén en uso
**R.N.05.** Cambio de estado al superar uso máximo.
**R.N.06.** Cambio de estado al iniciar reparación.
**R.N.07.** Cambio de estado al terminar reparacion.
**R.N.08.** Cambios de estado al iniciar alquiler.
**R.N.09.** Cambios de estado al finalizar alquiler
**R.N.10.** Cambio de estado al recibir valoración baja
'''
end note
note left of Vehiculo1: {completa, disjunta}


object Estacion1 {
    nombre= Reina Mercedes
    /numeroVehiculos= 1
    borrado= False
}

object Enganche1 {
    número= 1
    /estado= ocupado
    borrado= False
}
note top
'''
 **R.N.08.** Cambios de estado al iniciar alquiler.
 **R.N.09.** Cambios de estado al finalizar alquiler.
'''
end note

object Estacion2 {
    nombre= La Torre del Oro
    /numeroVehiculos= 0
    borrado= False
}

object Enganche2 {
    número= 1
    /estado= libre
    borrado= False
}
note top
'''
 **R.N.08.** Cambios de estado al iniciar alquiler.
 **R.N.09.** Cambios de estado al finalizar alquiler.
'''
end note

object Bicicleta1 {
    tipoBici= individual
}


Usuario1 <|-- Cliente1
Usuario2 <|-- TecnicoMantenimiento1

Enganche1 "*"--* Estacion1 : pertenece a >
Enganche2 "*"--* Estacion2 : pertenece a >

'Relación directa valoraciones'
Alquiler1 "1"--"*" Valoracion1 : pone >
Valoracion1 "*"--* Vehiculo1 : recibe <

TecnicoMantenimiento1 "1"--"*" Reparacion1 : realiza >
Reparacion1 "*"--* Vehiculo1 : recibe <

Enganche1 "1" --"1" Alquiler1: termina en <
Enganche2 "1" --"1" Alquiler1: inicia en <



'Relacion de Alquileres'
Cliente1 "1"--"*"  Alquiler1: realiza >
 
Alquiler1 "*"--"1" Vehiculo1: de

'Relacion Pago'
Cliente1 *--"*" Pago1
Pago1 "0..1"--"0..1" Alquiler1

Vehiculo1 <|-- Bicicleta1


@enduml